Fix Delete an attachment from base set needs remap tiles (fix aseprite/Attachment-System#42)
aseprite/Attachment-System pull request #57
Opened 2023-02-14 19:12 UTC by Gasparoken

Also removed an unused variable.

fix aseprite/Attachment-System#42

2023-02-14 19:21 UTC, dacap commented
Remember that the delete() function should still work as it was working for non-base folders (I didn't see the PR in detail).

2023-02-14 19:30 UTC, Gasparoken commented
Yes, you're right. I need to fix the 'tile_view' position in all non-base folders.

Question:
There are other options when an 'attachment' via 'tile_view' is deleted:
1. Pull one tile to the left, all the right attachments (implemented)
2. Do nothing with the others attachments
3. Pull a tile up, all the attachments that are below the deleted attachment.

2023-02-15 14:12 UTC, Gasparoken commented
Ready for review. This last commit adjusts tile indices, tile position in 'tile_view', and manages the tileset in base and non-base folders.

2023-02-15 15:50 UTC, dacap requested changes
Some changes required as a folder can have several instances of the same tile index (ti). And some duplicated code can be merged.

2023-02-15 15:50 UTC, dacap commented on plugin.lua
> +    local ti_item = find_item_by_tile(_folder, ti)
find_item_by_tile() implies that the folder can contain only one instance of the ti, but it can happen that a folder has two or more references to the same ti.

2023-02-15 15:50 UTC, dacap commented on plugin.lua
> +    for i=#_folder.items,1,-1 do
I'd highly recommend to create one `remove_tile_from_folder()` outside `show_tile_context_menu()` to avoid:

1. duplicated code, and
2.  this `_folder` variable and any confusion with the `folder` variable

With one `remove_tile_from_folder()` we can send an `adjustIndexes` param:

```lua
local function remove_tile_from_folder(folder, ti, adjustIndexes)
  ...
end
```

because the adjustment must be done in all folders anyway if the tile is deleted from the base folder (and it's done below).

2023-02-15 15:50 UTC, dacap commented on plugin.lua
> +              end
As said above, this is almost the same code as in `remove_tile_from_base_folder()`. I think we could just use one `remove_tile_from_folder()` , something like:

```lua
  local function delete()
    ...
        local adjustIndexes = db.isBaseSetFolder(folder)
        for i=1,#folders, 1 do
          remove_tile_from_folder(folders[i], ti, adjustIndexes)
        end
    ...
  end
```

2023-02-15 16:38 UTC, Gasparoken commented
> Some changes required as a folder can have several instances of the same tile index (ti). And some duplicated code can be merged.

Thanks for the review. Does it any sense to allow duplicate attachments visualization in non-base folders? Anyway I will fix it to take into account this case.

2023-02-15 17:14 UTC, dacap commented
> Does it any sense to allow duplicate attachments visualization in non-base folders?

Not sure if this will be used, but it's possible with the current impl (dropping several times the same tile in any folder, even in the base folder). Probably good for 2D arrangement. Anyway it's not a limitation and is not hard to handle these cases.

2023-02-15 20:10 UTC, Gasparoken commented
Ready for review. Just a side note: if we create a duplicate tile (same index) in the base folder, it can't be deleted (because it's 'Used' and the tile is in the base folder)

2023-02-15 22:02 UTC, dacap commented on plugin.lua
> +        end
I'll merge this commit removing these lines (because I think they do nothing). Also with some minor change like renaming `remove_tile_via_index_from_folder` with `remove_tile_from_folder_by_index`.

2023-02-15 22:07 UTC, dacap commented
> if we create a duplicate tile (same index) in the base folder, it can't be deleted (because it's 'Used' and the tile is in the base folder)

How is this? I tried and I was able to delete a duplicated (unused) tile from the base folder (two items pointing to the same tile index, but unused). E.g. here two items with tile index = 8:

Step 1:
![Screenshot from 2023-02-15 19-06-08](https://user-images.githubusercontent.com/39654/219183614-06640c59-023b-4260-8224-4ed5caa16983.png)

Step 2:
![Screenshot from 2023-02-15 19-06-13](https://user-images.githubusercontent.com/39654/219183672-4b626c94-bf01-457b-8e0e-13844a1f14e5.png)

Step 3:
![Screenshot from 2023-02-15 19-06-20](https://user-images.githubusercontent.com/39654/219183749-32905727-436a-453e-9a17-d39d7d6efe89.png)

2023-02-15 22:23 UTC, dacap commented
Merged in c662632d698668ee0d010d8325dea15912f68577 :+1:

2023-02-15 22:23 UTC, closed without merging

2023-02-16 11:35 UTC, Gasparoken commented
> How is this? I tried and I was able to delete a duplicated (unused) tile from the base folder (two items pointing to the same tile index, but unused). E.g. here two items with tile index = 8:

Excuse me, the correct sentence is:
... if we create a duplicate of **a used** tile (same index) in the base folder, it can't be deleted (because it's 'Used' and the tile is in the base folder).

How we can do this?
- Create a new folder
- Drag and drop a used tile to the new non-base folder
- Drag and drop the latest new tile to a new position in the base folder.
- Result: you'll get two used tiles in the base folder which cannot be deleted.

I'll create an issue for this.

2023-02-16 11:37 UTC, Gasparoken commented on plugin.lua
> +        end
Yes, you're right!